version: "3.3"
networks:
  devops:
    driver: bridge
volumes:
  PGDATA:
services:
  pgmoviedb:
    image:  codesenju/pgmoviedb.api.local:k8s
    build: ./postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
       - POSTGRES_DB=movie
       - POSTGRES_PASSWORD=12345
    volumes:
       - PGDATA:/var/lib/postgresql/data
    networks:
      - devops
    ports:
      - 5432:5432
  nodeapi:
    image:   codesenju/nodeapi.api.local:k8s
    build: ./nodeapi
    container_name: nodeapi
    environment:
       - DB_HOST=pgmoviedb
       - DB_PASSWORD=12345
       - DB_NAME=movie
       - DB_PORT=5432
       - DB_USER=postgres
    restart: unless-stopped
    networks:
      - devops
    ports:
      - 3000:3000
  index:
    image:  codesenju/index.api.local:k8s
    build: ./index.api.local
    container_name: index
    restart: unless-stopped
    networks:
      - devops
#    ports:
#      - 81:5000
  indexv2:
    image:  indexv2.api.local:k8s
    build: ./indexv2.api.local
    container_name: indexv2
    restart: unless-stopped
    networks:
      - devops
#    ports:
#      - 82:5000
  indexv3:
    image:  indexv3.api.local
    build: ./indexv3.api.local
    container_name: indexv3
    restart: unless-stopped
    networks:
      - devops
#    ports:
#      - 83:5000
  frontend:
    image:  codesenju/frontend.api.local:k8s
    build: ./frontend.api.local
    container_name: frontend
    restart: unless-stopped
    networks:
      - devops
    ports:
      - 5000:5000
  index-backend:
    image:  index-backend.api.local:k8s
    build: ./index-backend.api.local
    container_name: index-backend
    restart: unless-stopped
    networks:
      - devops
#    ports:
#      - 84:5000