version: "3.3"
networks:
  devops:
    driver: bridge
volumes:
  PGDATA:
services:
  pgmoviedb.service.local:
    image: pgmoviedb.service.local
    build: ./postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
       - POSTGRES_DB=movie
       - POSTGRES_PASSWORD=12345
    volumes:
       - PGDATA:/var/lib/postgresql/data
    networks:
      - devops
    ports:
      - 5432:5432
  nodeapi.service.local:
    image:   nodeapi.service.local
    build: ./nodeapi
    container_name: nodeapi
    restart: unless-stopped
    networks:
      - devops
    ports:
      - 3000:3000
  frontend.service.local:
    image:  frontend.service.local
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    networks:
      - devops
    ports:
      - 8080:5000