version: "3.3"
networks:
  devops:
    driver: bridge
volumes:
  PGDATA:
services:
  service.local.pgmoviedb:
    image: service.local.pgmoviedb
    build: ./postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
       - POSTGRES_DB=movie
       - POSTGRES_PASSWORD=12345
    volumes:
       - PGDATA:/var/lib/postgresql/data
    networks:
      - devops
    ports:
      - 5432:5432
  sservice.local.nodeapi:
    image:   service.local.nodeapi
    build: ./nodeapi
    container_name: nodeapi
    restart: unless-stopped
    networks:
      - devops
    ports:
      - 8080:3000